require 'date'
require 'uri'
require 'net/http'
require 'csv'
require 'json'
require 'json-schema'
require 'rest-client'
require 'zip'
require 'ruby_dig'

require 'datapackage/version'
require 'datapackage/exceptions'
require 'datapackage/schema'
require 'datapackage/validator'
require 'datapackage/resource'
require 'datapackage/package'
require 'datapackage/registry'
