require 'date'
require 'uri'
require 'net/http'
require 'csv'
require 'json'
require 'json-schema'
require 'zip'
require 'ruby_dig'
require 'tableschema'

require_relative 'datapackage/defaults'
require_relative 'datapackage/helpers'
require_relative 'datapackage/version'
require_relative 'datapackage/exceptions'
require_relative 'datapackage/profile'
require_relative 'datapackage/resource'
require_relative 'datapackage/package'
require_relative 'datapackage/registry'
